// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Proto/message.proto

package Distribuidos2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageInter struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageInter) Reset()         { *m = MessageInter{} }
func (m *MessageInter) String() string { return proto.CompactTextString(m) }
func (*MessageInter) ProtoMessage()    {}
func (*MessageInter) Descriptor() ([]byte, []int) {
	return fileDescriptor_9442aed4be7f2922, []int{0}
}

func (m *MessageInter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInter.Unmarshal(m, b)
}
func (m *MessageInter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInter.Marshal(b, m, deterministic)
}
func (m *MessageInter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInter.Merge(m, src)
}
func (m *MessageInter) XXX_Size() int {
	return xxx_messageInfo_MessageInter.Size(m)
}
func (m *MessageInter) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInter.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInter proto.InternalMessageInfo

func (m *MessageInter) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type MessageFin struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageFin) Reset()         { *m = MessageFin{} }
func (m *MessageFin) String() string { return proto.CompactTextString(m) }
func (*MessageFin) ProtoMessage()    {}
func (*MessageFin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9442aed4be7f2922, []int{1}
}

func (m *MessageFin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageFin.Unmarshal(m, b)
}
func (m *MessageFin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageFin.Marshal(b, m, deterministic)
}
func (m *MessageFin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageFin.Merge(m, src)
}
func (m *MessageFin) XXX_Size() int {
	return xxx_messageInfo_MessageFin.Size(m)
}
func (m *MessageFin) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageFin.DiscardUnknown(m)
}

var xxx_messageInfo_MessageFin proto.InternalMessageInfo

func (m *MessageFin) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageInter)(nil), "grpc.MessageInter")
	proto.RegisterType((*MessageFin)(nil), "grpc.MessageFin")
}

func init() { proto.RegisterFile("Proto/message.proto", fileDescriptor_9442aed4be7f2922) }

var fileDescriptor_9442aed4be7f2922 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0x4b, 0x86, 0x40,
	0x10, 0x40, 0x59, 0x90, 0xc0, 0xb1, 0x43, 0x4c, 0x97, 0xf0, 0x64, 0x76, 0xf1, 0xb4, 0x1b, 0x76,
	0xea, 0x1a, 0x21, 0x04, 0x05, 0xd1, 0xb1, 0xdb, 0xac, 0x8a, 0x0d, 0xe8, 0x8e, 0xec, 0xae, 0x90,
	0xfd, 0xfa, 0xd0, 0x3a, 0x14, 0x9f, 0xb7, 0x99, 0xc7, 0x63, 0x1e, 0x03, 0x97, 0xaf, 0x5e, 0xa2,
	0x98, 0xa9, 0x0f, 0x81, 0x86, 0x5e, 0xcf, 0xdb, 0x86, 0xc9, 0xe0, 0xe7, 0xb6, 0x2c, 0xe1, 0xfc,
	0xe5, 0x07, 0x3f, 0xb9, 0xd8, 0x7b, 0x44, 0x48, 0xac, 0x74, 0xeb, 0x95, 0x2a, 0x54, 0x95, 0xbe,
	0xed, 0x73, 0x59, 0x00, 0xfc, 0x3a, 0x0d, 0xbb, 0x23, 0xa3, 0x5e, 0x21, 0x7b, 0x26, 0x2b, 0x9e,
	0xa2, 0x78, 0x16, 0xbc, 0x87, 0x6c, 0xbf, 0xd6, 0xd2, 0x64, 0x59, 0x10, 0xf5, 0x96, 0xd2, 0x7f,
	0x3b, 0xf9, 0x01, 0xab, 0xd4, 0xad, 0x42, 0x03, 0x69, 0xc3, 0x8e, 0x46, 0xfe, 0x22, 0x8f, 0x17,
	0xff, 0xa4, 0x86, 0x5d, 0x7e, 0x42, 0x1e, 0x6e, 0xde, 0xaf, 0x07, 0x8e, 0x1f, 0x8b, 0xd5, 0xad,
	0x4c, 0x86, 0x1c, 0x5b, 0x1a, 0xe5, 0xd3, 0x3c, 0x72, 0x88, 0x9e, 0xed, 0xc2, 0x9d, 0x84, 0xda,
	0x9e, 0xed, 0x2f, 0xdf, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x67, 0x4a, 0x64, 0x09, 0x01,
	0x00, 0x00,
}
